service: SweatWorks

provider:
  name: aws
  runtime: nodejs8.10

custom:
  dynamodb:
    start:
      port: 8001
      inMemory: true # DynamoDB will run in memory, instead of using a database file. When you stop DynamoDB, none of the data will be saved.
      migrate: true # After starting DynamoDB local, create DynamoDB tables from the Serverless configuration.
      seed: true # After starting and migrating dynamodb local, injects seed data into your tables.
    seed:
      authors:
        sources:
          - table: authorsTable
            sources: [./seeds/authors.json]
      publications:
        sources:
          - table: publicationsTable
            sources: [./seeds/publications.json]            

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: authorsTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    publicationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: publicationsTable
        AttributeDefinitions:
          - AttributeName: datetime
            AttributeType: S
          - AttributeName: title
            AttributeType: S            
        KeySchema:
          - AttributeName: datetime
            KeyType: HASH
          - AttributeName: title
            KeyType: RANGE            
        BillingMode: PAY_PER_REQUEST          

functions:
  hello:
    handler: functions/author/getAuthor.handler
    events:
      - http:
          path: author
          method: get

plugins:
  - serverless-dynamodb-local
  - serverless-offline